### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by thiphariel** [pydio/cells#11]
Hi.

I try since days to install pydio cells on my server (debian 9 & also Arch tested) but I always faced to this issue : 

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xfb2a0a]

goroutine 96 [running]:
github.com/pydio/cells/vendor/github.com/micro/go-web.(*service).Init(0xc4246b5cc0, 0xc4245ee980, 0x7, 0x7, 0x24, 0x1)
	/opt/JetBrains/TeamCity/buildAgent/work/73afa92fb1a910b1/src/github.com/pydio/cells/vendor/github.com/micro/go-web/service.go:298 +0x31a
github.com/pydio/cells/common/service.WithWeb.func1.2(0x5f954c0, 0xc4247c4600, 0x0, 0x0)
	/opt/JetBrains/TeamCity/buildAgent/work/73afa92fb1a910b1/src/github.com/pydio/cells/common/service/service-web.go:83 +0x4ba
github.com/pydio/cells/common/service.(*service).Start(0xc4247c4600)
	/opt/JetBrains/TeamCity/buildAgent/work/73afa92fb1a910b1/src/github.com/pydio/cells/common/service/service.go:320 +0x20a
created by github.com/pydio/cells/cmd.glob..func20
	/opt/JetBrains/TeamCity/buildAgent/work/73afa92fb1a910b1/src/github.com/pydio/cells/cmd/services-start.go:147 +0xa3
```

Here is my installation : 

```

$ ./cells install

Welcome to Pydio Cells Home Edition installation
Pydio Cells Home Edition will be configured to run on this machine. Make sure to prepare the following data
 - IPs and ports for binding the webserver to outside world
 - MySQL 5.6+ (or MariaDB equivalent) server access
 - PHP-FPM 7+ for running frontend
Pick your installation mode when you are ready.

✔ Command line (performed in this terminal)
Use the arrow keys to navigate: ↓ ↑ → ←
✔ 0.0.0.0:8080
✔ External Host (used to access this machine from outside world if it differs from Bind Host): 0.0.0.0:8080
✔ Disable SSL (not recommended)

## Database Connection
✔ TCP
✔ Database Hostname: localhost
✔ Database Port: 3306
✔ Database Name: cells
✔ Database User: pydio
✔ Database Password (leave empty if not needed): ***********
✔ Successfully connected to the database

## Frontend Configuration
✔ Php version detected: 7.2.8
✗ PHP-FPM Listen Address was detected at /run/php/php7.2-fpm.sock. Is it correct:
✔ Please enter the address where Php-FPM is listening (use host:port or /path/to/socket): /run/php/php7.2-fpm.sock
✔ Php-Fpm successfully connected
✔ Admin Login (leave passwords empty if an admin is already created): Thiphariel
✔ Admin Password: ***********
✔ Confirm Password: ***********

## Advanced Settings
✗ There are some advanced settings for ports and initial data storage. Do you want to edit them:

## Performing Installation
2018-08-08T07:44:19.050Z	INFO	Starting installation now	{"bindUrl": "http://0.0.0.0:8080"}
✔ Created main database
✔ Created default datasources
✔ Configuration of gateway services
✔ Deploying interface assets: this may take some time...
✔ Deploying interface assets: 10% done...
✔ Deploying interface assets: 20% done...
✔ Deploying interface assets: 30% done...
✔ Deploying interface assets: 40% done...
✔ Deploying interface assets: 50% done...
✔ Deploying interface assets: 60% done...
✔ Deploying interface assets: 70% done...
✔ Deploying interface assets: 80% done...
✔ Deploying interface assets: 90% done...
2018-08-08T07:44:41.794Z	INFO	Extracted 8404 files for a total size of 98169104
✔ Deploying interface assets: 100% done...
✔ Interface assets: Copied 8404 files
Writing file /home/pydio/.config/pydio/cells/static/pydio/data/plugins/boot.conf/bootstrap.json
✔ Created interface config files

✔ Installation Finished: please restart with './cells start' command
```

My setup is : 

```
php 7.2.8
mariadb 10.3.8
pydio cells 1.0.1
```

Any idea ?
Thanks !

**Comment by bsinou** [comment]
Hello, 

as quoted in the [contributing document](https://github.com/pydio/cells/blob/master/CONTRIBUTING.md#contributing-to-pydio-cells), you should really ask these kind of question in the [Pydio forum](https://forum.pydio.com).

Thus said, even if lacking information about your network infrastructure, your error looks like you have a problem with the missing private IP address. You should have a look at [this thread](https://forum.pydio.com/t/pydio-cells-not-working/1182/6) in the forum. On our side, we will work on this error to provide the user with a more explicit message when this problem arises.

Regards.

**Comment by thiphariel** [comment]
Allright, thanks for give me a clue, I'll investigate an give an answer here if I succeed.

Cheers
