### ISSUE TITLE
cells configure raises panic while configuring S3 compatible storage

### ISSUE THREAD

**Issue by vctmohan** [pydio/cells#409]
I have been trying to install and test pydio cells functionality. I tried to configure and use pydio with Amazon S3 for data storage. I encountered issues while trying to configure cells with Amazon S3 storage.

Here is the relevant part of "./cells configure" output:

```
## Default storage location
Use the arrow keys to navigate: ↓ ↑ → ←
✔ Store data in S3-compatible storage (requires api key/secret)
For S3 compatible storage, please provide storage URL (leave empty for Amazon):
✔ Provide storage custom region (leave empty for default): 
Please enter S3 Api Key: AHXGM6LNNAEJ5PYAVNLY
Please enter S3 Api Secret: ****************************************
✔ Successfully connected to S3 and list buckets
✔ Successfully connected to S3, listed 16 buckets, ability to create: true
Select a unique prefix for this installation buckets.: drive-demo-
✔ Buckets used for installing cells were correctly detected (drive-demo-pydiods1, drive-demo-personal, drive-demo-cellsdata, drive-demo-binaries,drive-demo-thumbs, drive-demo-versions)

## Applying configuration
... Starting installation now
... Generating secrets
... Created main database
panic: assignment to entry in nil map

goroutine 1 [running]:
github.com/pydio/cells/v4/discovery/install/lib.actionDatasourceAdd(0xc000fbc280, 0x0, 0x0)
        /mnt/d/Development/Drive/pydio-cells-repo/discovery/install/lib/datasource.go:104 +0x15e8
github.com/pydio/cells/v4/discovery/install/lib.Install(0xaeaa760, 0xc0000740a0, 0xc000fbc280, 0x1, 0xa46b0d8, 0x0, 0x0)
        /mnt/d/Development/Drive/pydio-cells-repo/discovery/install/lib/installer.go:77 +0x5e5
github.com/pydio/cells/v4/cmd.cliInstall(0xd3c8cc0, 0xd39d280, 0x0, 0x0, 0x0)
        /mnt/d/Development/Drive/pydio-cells-repo/cmd/install-cli.go:107 +0x94f
github.com/pydio/cells/v4/cmd.glob..func61(0xd3c8cc0, 0xd5e86d0, 0x0, 0x0)
        /mnt/d/Development/Drive/pydio-cells-repo/cmd/configure.go:273 +0x778
github.com/spf13/cobra.(*Command).execute(0xd3c8cc0, 0xd5e86d0, 0x0, 0x0, 0x0, 0x0)
        /home/mohan/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:860 +0xe5d
github.com/spf13/cobra.(*Command).ExecuteC(0xd3c8f40, 0xd3c8cc0, 0x0, 0x0)
        /home/mohan/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:974 +0x765
github.com/spf13/cobra.(*Command).Execute(0xd3c8f40, 0x0, 0x0)
        /home/mohan/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:902 +0x3b
github.com/spf13/cobra.(*Command).ExecuteContext(0xd3c8f40, 0xaeaa728, 0xc0026f4a00, 0x0, 0x0)
        /home/mohan/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:895 +0x6a
github.com/pydio/cells/v4/cmd.Execute()
        /mnt/d/Development/Drive/pydio-cells-repo/cmd/root.go:135 +0xf7
main.main()
        /mnt/d/Development/Drive/pydio-cells-repo/main.go:122 +0x70
```

Any help in resolving this would be greatly appreciated.

**Comment by cdujeu** [comment]
Hello @vctmohan can you give more info about your build ? Are you using official binaries or building from source ? If so, which branch?

**Comment by vctmohan** [comment]
> Hello @vctmohan can you give more info about your build ? Are you using official binaries or building from source ? If so, which branch?

I initially tried an official 3.0.6 binary and later built from the github main repo. It got into exactly same issue with the both.

**Comment by vctmohan** [comment]
I just tried the same with "pydio-cells-3.0.6-linux-amd64.zip" downloaded from Pydio website. I got into the same issue with this version as well. 

```
## Applying configuration
... Starting installation now
... Created main database
panic: assignment to entry in nil map

goroutine 1 [running]:
github.com/pydio/cells/discovery/install/lib.actionDatasourceAdd(0xc0005d8240, 0xc00130fb60, 0x0)
        github.com/pydio/cells/discovery/install/lib/datasource.go:104 +0xbb2
github.com/pydio/cells/discovery/install/lib.Install(0x75d7940, 0xc000122000, 0xc0005d8240, 0x1, 0x72059a8, 0x23, 0x0)
        github.com/pydio/cells/discovery/install/lib/installer.go:65 +0x366
github.com/pydio/cells/cmd.cliInstall(0x8d1d800, 0x8d05060, 0x0, 0x8d05060, 0x0)
        github.com/pydio/cells/cmd/install-cli.go:99 +0x3e7
github.com/pydio/cells/cmd.glob..func68(0x8d1d800, 0x930f480, 0x0, 0x0)
        github.com/pydio/cells/cmd/configure.go:270 +0x49f
github.com/pydio/cells/vendor/github.com/spf13/cobra.(*Command).execute(0x8d1d800, 0x930f480, 0x0, 0x0, 0x8d1d800, 0x930f480)
        github.com/pydio/cells/vendor/github.com/spf13/cobra/command.go:854 +0x2c2
github.com/pydio/cells/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x8d1dd40, 0xc000122000, 0x75d7900, 0xc000dad5c0)
        github.com/pydio/cells/vendor/github.com/spf13/cobra/command.go:958 +0x375
github.com/pydio/cells/vendor/github.com/spf13/cobra.(*Command).Execute(...)
        github.com/pydio/cells/vendor/github.com/spf13/cobra/command.go:895
github.com/pydio/cells/vendor/github.com/spf13/cobra.(*Command).ExecuteContext(...)
        github.com/pydio/cells/vendor/github.com/spf13/cobra/command.go:888
github.com/pydio/cells/cmd.Execute()
        github.com/pydio/cells/cmd/root.go:432 +0xc8
main.main()
        github.com/pydio/cells/main.go:116 +0x68
```

**Comment by cdujeu** [comment]
Hello @vctmohan this should be fixed in the main branch. We will probably backport the fix to the 3.X as well.

**Comment by vctmohan** [comment]
Thank you. I just checked and the fix seemed to be working fine. I am closing this issue.
