### ISSUE TITLE
cannot install (cells.exe configure)

### ISSUE THREAD

**Issue by user4302** [pydio/cells#524]
_Note: This issue tracker is only used for reporting **qualified bugs**. Use [Pydio Forums](https://forum.pydio.com) for support or feature requests: first-start, install, or config-related troubleshootings will be ignored and closed! Otherwise, please **fill all sections below**._  

**📝 Describe the bug**

 - A clear and concise description of what the bug is.
 - If applicable, add screenshots to help explain your problem.
 - A clear and concise description of what you expected to happen.

when i run cells.exe configure i get the cli prompt to select the browser or cli mode
if i select either i get a different error

**⚙️ How-to Reproduce**

on win10 pro cmd

1. scenario 1
a. run cells.exe configure
b. select browser as the option (i get error1 (i added the code at the bottom))

2. scenario 2
a. run cells.exe configure
b. select cli as the option and select TCP (i get error2 (i added the code at the bottom))

3. scenario 3
a. run cells.exe configure
b. select cli as the option and select TCP
c. i set a db password this time
d. i get a successful installation, but the config.json nor the certificate files are created even though it asks me to run cells.exe start
e. i run cells.exe start (i get error3 (i added the code at the bottom))

**🩺 Environment / Setup**

Complete the following information:

Server Versions:
 - Cells Version: v4.3.2
 - MariaDB/MySQL version
 - Server OS: windows 10 
 - Other dependencies (MongoDB, Nats, ETCd, etc)

Client used for testing: 
 - Client OS / mobile device, etc...
 
Additional context:
error1:
```
D:\pydio-cells-4.3.2-windows-amd64>cells.exe configure

Welcome to Pydio Cells Home Edition installation
Pydio Cells Home Edition (v4.3.2) will be configured to run on this machine.
Make sure to prepare access and credentials to a MySQL 5.6+ (or MariaDB equivalent) server.
Pick your installation mode when you are ready.

v Browser-based (requires a browser access)

Installation Server is starting...
Listening to: https://0.0.0.0:8080

2023-12-23T03:52:43.915+0530    INFO    pydio.rest.install      starting        {"service": "pydio.rest.install", "hook router to": "/a/install"}
2023-12-23T03:52:43.915+0530    INFO    pydio.rest.config       starting        {"service": "pydio.rest.config", "hook router to": "/a/config"}
2023-12-23T03:52:43.915+0530    INFO    pydio.web.install       ready
2023-12-23T03:52:44.120+0530    INFO    pydio.rest.install      ready
2023-12-23T03:52:44.120+0530    INFO    pydio.rest.config       ready
2023-12-23T03:52:44.160+0530    INFO    pydio.server.caddy      ✅ Using the local CA at "rootCA.pem" ✨
2023-12-23T03:52:44.420+0530    INFO    pydio.server.caddy      ✅ Created a new certificate valid for the following names 📜
2023-12-23T03:52:44.420+0530    INFO    pydio.server.caddy       - "127.0.0.1"
2023-12-23T03:52:44.420+0530    INFO    pydio.server.caddy       - "x.x.x.x"
2023-12-23T03:52:44.420+0530    INFO    pydio.server.caddy       - "x.x.x.x"
2023-12-23T03:52:44.421+0530    INFO    pydio.server.caddy       - "x.x.x.x"
2023-12-23T03:52:44.421+0530    INFO    pydio.server.caddy       - "kubernetes.docker.internal"
2023-12-23T03:52:44.421+0530    INFO    pydio.server.caddy      ✅ The certificate is at "x.pem"
 and the key at "x-key.pem"
2023-12-23T03:52:44.436+0530    INFO    pydio.server.caddy
2023-12-23T03:52:44.436+0530    INFO    pydio.server.caddy
2023-12-23T03:52:44.436+0530    INFO    pydio.server.caddy      👉 If you are behind a reverse proxy, you can either install the RootCA on the proxy machine trust store, or configure your proxy to `insecure_skip_verify` for pointing to Cells.
2023-12-23T03:52:44.436+0530    INFO    pydio.server.caddy      👉 If you are developing locally, you may install the RootCA in your system trust store to see a green light in your browser!
2023-12-23T03:52:44.436+0530    INFO    pydio.server.caddy      🗒  To easily install the RootCA in your trust store, use https://github.com/FiloSottile/mkcert. Set the $CAROOT environment variable to the rootCA folder then use 'mkcert -install'
2023-12-23T03:52:44.436+0530    INFO    pydio.server.caddy
2023-12-23T03:52:44.438+0530    WARN    pydio.server.caddy      admin - admin endpoint disabled
2023-12-23T03:52:44.447+0530    INFO    pydio.server.caddy      tls.cache.maintenance - started background certificate maintenance{"cache": "0xc000ee7100"}
2023-12-23T03:52:44.447+0530    INFO    pydio.server.caddy      tls.cache.maintenance - stopped background certificate maintenance{"cache": "0xc000ee7100"}
panic: server.Start caddy: loading new config: loading http app module: provision http: getting tls app: loading tls app module: provision tls: loading certificates: open C:\Users\Admin\AppData\Roaming\Pydio\cells\certs\x.pem: The system cannot find the path specified.

goroutine 84 [running]:
github.com/pydio/cells/v4/cmd.performBrowserInstall.func1({0x907b240?, 0xc000dc81c8?})
        github.com/pydio/cells/v4/cmd/configure.go:347 +0x26
github.com/pydio/cells/v4/common/runtime/manager.(*manager).ServeAll.func5()
        github.com/pydio/cells/v4/common/runtime/manager/manager.go:263 +0x3d
created by github.com/pydio/cells/v4/common/runtime/manager.(*manager).ServeAll in goroutine 1
        github.com/pydio/cells/v4/common/runtime/manager/manager.go:270 +0x66c

D:\pydio-cells-4.3.2-windows-amd64>
```
error2:
```
D:\pydio-cells-4.3.2-windows-amd64>cells.exe configure

Welcome to Pydio Cells Home Edition installation
Pydio Cells Home Edition (v4.3.2) will be configured to run on this machine.
Make sure to prepare access and credentials to a MySQL 5.6+ (or MariaDB equivalent) server.
Pick your installation mode when you are ready.

v Command line (performed in this terminal)

Database Hostname: localhost
Database Port: 3306
Database Name: cells
Database User: root
Database Password (leave empty if not needed):
x Cannot connect to database, please review the parameters: Error 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)
Use the arrow keys to navigate: ↓ ↑ → ←
? Database Connection Type:
  > TCP
    Socket
    Manual
```

error3:
```
D:\pydio-cells-4.3.2-windows-amd64>cells.exe start

x We cannot find a configuration file ... C:\Users\Admin\AppData\Roaming\Pydio\cells\pydio.json

? Do you want to create one now? [y/N] █
```

**Comment by cdujeu** [comment]
hello @user4302 , we've been retesting windows recently but did not get issues during installation - would you mind giving a try with the latest version?

**Comment by waterver** [comment]
I do have the same problem.
When I finish configure(both termial and browser), it shows not found confuguration file.
Version:4.4.3 

Installation Server is starting...
Listening to: http://localhost:8080

2024-07-20T14:22:15.470+0800    INFO    pydio.rest.install      starting        {"service": "pydio.rest.install", "hook router to": "/a/install"}
2024-07-20T14:22:15.471+0800    INFO    pydio.rest.config       starting        {"service": "pydio.rest.config", "hook router to": "/a/config"}
2024-07-20T14:22:15.471+0800    INFO    pydio.web.install       ready
2024-07-20T14:22:15.471+0800    INFO    pydio.rest.install      ready
2024-07-20T14:22:15.471+0800    INFO    pydio.rest.config       ready
2024-07-20T14:22:15.474+0800    WARN    pydio.caddy.admin       admin endpoint disabled
2024-07-20T14:22:15.474+0800    INFO    pydio.caddy.http.log    server running  {"name": "srv0", "protocols": ["h1","h2","h3"]}
2024-07-20T14:22:15.474+0800    INFO    pydio.caddy.http        servers shutting down with eternal grace period
Adding admin credentials to config, to be inserted at next start
2024-07-20T14:22:42.747+0800    INFO            Install done: trigger onSuccess now
Browser install is finished. Stopping server in 5s...

x We cannot find a configuration file ... C:\Users\waterver\AppData\Roaming\Pydio\cells\pydio.json

? Do you want to create one now? [y/N]
