### ISSUE TITLE
Go Panic on install

### ISSUE THREAD

**Issue by jradxl** [pydio/cells#64]
Hi,
I've downloaded the home edition of Cells Linux v1.2.5 from your website and via wget, and both ./cells install and ./cells install-cli give a Go Panic.

lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.7 (stretch)
Release:	9.7
Codename:	stretch

What do you advise?

```
panic: runtime error: slice bounds out of range
goroutine 1 [running]:
github.com/pydio/cells/vendor/github.com/godbus/dbus.getSessionBusPlatformAddress(0x341aa93, 0x18, 0x0, 0x0)
	/opt/teamcity/agent/work/b7c550f2c973b54c/src/github.com/pydio/cells/vendor/github.com/godbus/dbus/conn_other.go:30 +0x2ac
github.com/pydio/cells/vendor/github.com/godbus/dbus.getSessionBusAddress(0x0, 0x0, 0x0, 0x0)
	/opt/teamcity/agent/work/b7c550f2c973b54c/src/github.com/pydio/cells/vendor/github.com/godbus/dbus/conn.go:96 +0xe5
github.com/pydio/cells/vendor/github.com/godbus/dbus.SessionBusPrivate(0x8, 0x69ffc10, 0xc4222fd508)
	/opt/teamcity/agent/work/b7c550f2c973b54c/src/github.com/pydio/cells/vendor/github.com/godbus/dbus/conn.go:101 +0x22
github.com/pydio/cells/vendor/github.com/godbus/dbus.SessionBus(0x0, 0x0, 0x0)
	/opt/teamcity/agent/work/b7c550f2c973b54c/src/github.com/pydio/cells/vendor/github.com/godbus/dbus/conn.go:73 +0xad
github.com/pydio/cells/vendor/github.com/zalando/go-keyring/secret_service.NewSecretService(0x7f2e03181000, 0x0, 0xc4222fd5a0)
	/opt/teamcity/agent/work/b7c550f2c973b54c/src/github.com/pydio/cells/vendor/github.com/zalando/go-keyring/secret_service/secret_service.go:50 +0x26
github.com/pydio/cells/vendor/github.com/zalando/go-keyring.secretServiceProvider.Get(0x3409e57, 0x13, 0x33f887b, 0xe, 0x0, 0x0, 0x0, 0x0)
	/opt/teamcity/agent/work/b7c550f2c973b54c/src/github.com/pydio/cells/vendor/github.com/zalando/go-keyring/keyring_linux.go:78 +0x39
github.com/pydio/cells/vendor/github.com/zalando/go-keyring.Get(0x3409e57, 0x13, 0x33f887b, 0xe, 0x3, 0xc420056070, 0xc420056000, 0xc4200d21d8)
	/opt/teamcity/agent/work/b7c550f2c973b54c/src/github.com/pydio/cells/vendor/github.com/zalando/go-keyring/keyring.go:32 +0x61
github.com/pydio/cells/common/crypto.GetKeyringPassword(0x3409e57, 0x13, 0x33f887b, 0xe, 0x0, 0x98, 0x3185220, 0xc4234681e0, 0x100000000000000, 0x0)
	/opt/teamcity/agent/work/b7c550f2c973b54c/src/github.com/pydio/cells/common/crypto/keyring.go:33 +0x56
github.com/pydio/cells/common/config/vault.(*VaultSource).initMasterPassword(0xc4233bfcc0)
	/opt/teamcity/agent/work/b7c550f2c973b54c/src/github.com/pydio/cells/common/config/vault/source.go:152 +0xe7
github.com/pydio/cells/common/config/vault.NewVaultSource(0xc422e0abd0, 0x30, 0xc422e0ac00, 0x2f, 0x0, 0x0, 0x0, 0x0, 0x0)
	/opt/teamcity/agent/work/b7c550f2c973b54c/src/github.com/pydio/cells/common/config/vault/source.go:51 +0x19d
github.com/pydio/cells/common/config.Vault.func1()
	/opt/teamcity/agent/work/b7c550f2c973b54c/src/github.com/pydio/cells/common/config/secrets.go:47 +0x398
sync.(*Once).Do(0x8b451e0, 0x69fdd78)
	/usr/local/go/src/sync/once.go:44 +0xbe
github.com/pydio/cells/common/config.Vault(0xc4233eb050, 0x2be8440)
	/opt/teamcity/agent/work/b7c550f2c973b54c/src/github.com/pydio/cells/common/config/secrets.go:28 +0x39
github.com/pydio/cells/common/config.Set(0x2be8440, 0xc423444110, 0xc423442b00, 0x2, 0x2)
	/opt/teamcity/agent/work/b7c550f2c973b54c/src/github.com/pydio/cells/common/config/vars.go:150 +0x183
github.com/pydio/cells/cmd.glob..func18(0x8967ca0, 0x8b45110, 0x0, 0x0)
	/opt/teamcity/agent/work/b7c550f2c973b54c/src/github.com/pydio/cells/cmd/install-cli.go:165 +0x7bc
github.com/pydio/cells/vendor/github.com/spf13/cobra.(*Command).execute(0x8967ca0, 0x8b45110, 0x0, 0x0, 0x8967ca0, 0x8b45110)
	/opt/teamcity/agent/work/b7c550f2c973b54c/src/github.com/pydio/cells/vendor/github.com/spf13/cobra/command.go:760 +0x2c1
github.com/pydio/cells/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x8967320, 0x1, 0x1, 0x69fe570)
	/opt/teamcity/agent/work/b7c550f2c973b54c/src/github.com/pydio/cells/vendor/github.com/spf13/cobra/command.go:846 +0x30a
github.com/pydio/cells/vendor/github.com/spf13/cobra.(*Command).Execute(0x8967320, 0xc4200b4058, 0x0)
	/opt/teamcity/agent/work/b7c550f2c973b54c/src/github.com/pydio/cells/vendor/github.com/spf13/cobra/command.go:794 +0x2b
github.com/pydio/cells/cmd.Execute()
	/opt/teamcity/agent/work/b7c550f2c973b54c/src/github.com/pydio/cells/cmd/root.go:196 +0x36
main.main()
	/opt/teamcity/agent/work/b7c550f2c973b54c/src/github.com/pydio/cells/main.go:111 +0x6a

```

**Comment by cdujeu** [comment]
Hi! Please post in the forum, we use github only for qualified issue !
Do not hesitate to add info about your linux flavor ...
